import {
  FiActivity,
  FiAlertTriangle,
  FiAward,
  FiBarChart2,
  FiBell,
  FiBookOpen,
  FiBriefcase,
  FiCalendar,
  FiCheck,
  FiCheckCircle,
  FiChevronLeft,
  FiChevronRight,
  FiClock,
  FiCoffee,
  FiDownload,
  FiDroplet,
  FiEdit3,
  FiFlag,
  FiHeart,
  FiHome,
  FiInfo,
  FiLayers,
  FiMinus,
  FiMoon,
  FiNavigation,
  FiPackage,
  FiPauseCircle,
  FiPlus,
  FiRefreshCw,
  FiSettings,
  FiStar,
  FiSun,
  FiTarget,
  FiTrash2,
  FiTrendingUp,
  FiUpload,
  FiX,
  FiZap
} from 'react-icons/fi';

const MAP = {
  sun: FiSun,
  train: FiNavigation,
  book: FiBookOpen,
  home: FiHome,
  meal: FiCoffee,
  sparkle: FiStar,
  pen: FiEdit3,
  pause: FiPauseCircle,
  rocket: FiBriefcase,
  dumbbell: FiActivity,
  shake: FiZap,
  moon: FiMoon,
  bed: FiMoon,
  chef: FiPackage,
  water: FiDroplet,
  check: FiCheck,
  checkCircle: FiCheckCircle,
  plus: FiPlus,
  minus: FiMinus,
  settings: FiSettings,
  trending: FiTrendingUp,
  calendar: FiCalendar,
  clock: FiClock,
  bell: FiBell,
  chevronRight: FiChevronRight,
  chevronLeft: FiChevronLeft,
  close: FiX,
  target: FiTarget,
  award: FiAward,
  layers: FiLayers,
  refresh: FiRefreshCw,
  download: FiDownload,
  upload: FiUpload,
  trash: FiTrash2,
  info: FiInfo,
  warning: FiAlertTriangle,
  flag: FiFlag,
  heart: FiHeart,
  chart: FiBarChart2
};

export default function Icon({ name, size = 20, ...rest }) {
  const Cmp = MAP[name] || FiInfo;
  return <Cmp size={size} aria-hidden="true" focusable="false" {...rest} />;
}

export const KIND_ICON = {
  supplements: 'sun',
  medicine: 'heart',
  meal: 'meal',
  water: 'water',
  selfcare: 'sparkle',
  study: 'pen',
  business: 'rocket',
  gym: 'dumbbell',
  prep: 'chef',
  sleep: 'moon',
  weight: 'trending',
  commute: 'train',
  school: 'book',
  rest: 'pause',
  mealprep: 'chef'
};

export const KIND_COLOR = {
  supplements: 'var(--warning)',
  medicine: 'var(--pink)',
  meal: 'var(--success)',
  water: 'var(--teal)',
  selfcare: 'var(--purple)',
  study: 'var(--accent)',
  business: 'var(--purple)',
  gym: 'var(--error)',
  prep: 'var(--warning)',
  mealprep: 'var(--warning)',
  sleep: 'var(--text-secondary)',
  weight: 'var(--accent)',
  commute: 'var(--text-secondary)',
  school: 'var(--accent)',
  rest: 'var(--text-secondary)'
};
